### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by nmarcetic** [dvonlehman/s3-proxy#2]
Hey @dvonlehman 
I just tried to use your module and got exception "undefined is not a function" from [aws-config](https://github.com/4front/aws-config) dep [is-ec2](https://github.com/dvonlehman/is-ec2). 
I saw issue with this already https://github.com/dvonlehman/is-ec2/issues/1 
Do you have any idea whats happening :) Thanks!

Cheers

**Comment by dvonlehman** [comment]
Hi @nmarcetic,

I commented on the is-ec2 issue at https://github.com/dvonlehman/is-ec2/issues/1#issuecomment-227319254. The error would imply that `child_process.execSync` is not defined. This was introduced way back in node 0.11.2. Which version of node are you running?

David

**Comment by nmarcetic** [comment]
Hi @dvonlehman 
Sorry for delay. I thing your are right ;) I use node  v0.10.42
